# Generated by Django 6.0.2 on 2026-03-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='image',
        ),
    ]
